---
title: "Titre de votre troisième R Markdown"
description: | 
  Petite description du contenu de cette page
date: "`r Sys.Date()`"
# Modifier les détails que vous voulez
author:
  - first_name: "Prénom"
    last_name: "Nom"
    url: https://github.com/votre-username
    # les champs d'affiliation sont optionnels, vous pouvez les
    # comment out en ajoutant un # devant.
    affiliation: FAS1002
    affiliation_url: https://admission.umontreal.ca/programmes/microprogramme-de-1er-cycle-en-analyse-des-megadonnees-en-sciences-humaines-et-sociales/structure-du-programme/
    # changer pour votre propre orcid id
    # https://orcid.org/ pour vous inscrire.
    orcid_id: 0000-0000-0000-0000
# Changer pour votre propre URL si jamais quelqu'un vous cite!
citation_url: https://fas1002.github.io/FAS1002_projet-final
# Inclure les références que vous utilisez dans vos rapports
# dans un fichier biblio.bib. Je conseille Zotero pour construire
# ce fichier ou d'utiliser le package citr dans RStudio.
# Installation: devtools::install_github("crsh/citr")
bibliography: references.bib
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
#MANIPULATION BANQUE DE DONNÉES DES VACCINS


#Je change le type de classe de la valeur location pour que ca soit 
#une variable catégorielle.
#Je recode les iso_code des pays qui n'était pas identifié par trois lettres
#Je recode les iso_codes des observations qui ont pour location : une catégorie
#socio-économique.
#Je déselectionne les variables que je considère moins importantes ou
#qui est remplit de NAs.  Par exemple total_boosters qui a surment été crée 
#seulement après la découverte de nouvelle variante néccésitant une 3iem dose.
# Si j'enlève les NAs à la fin, je coupe ma banque de données de 50%
vaxd <- vax_raw %>% 
    mutate(location=factor(location),
        iso_code=recode(iso_code, 
                         "OWID_KOS"="KOS",
                         "OWID_CYN"="CYN",
                         "OWID_SCT"="SCT",
                         "OWID_WLS"="WLS",
                         "OWID_ENG"="ENG",
                         "OWID_NIR"="NIR",
                         "OWID_UMC"="income",
                         "OWID_LIC"="income",
                         "OWID_HIC"="income",
                         "OWID_LMC"="income")) %>% 
    select(-c(total_vaccinations,daily_vaccinations_raw,total_boosters_per_hundred,total_boosters,daily_vaccinations_per_million,daily_people_vaccinated_per_hundred,daily_people_vaccinated,daily_vaccinations)) %>% 
  na.omit() # J'enlève les NA ici parce que trop de ne mettent pas tout les variables à jour quotidiennement mais une fois par semaine ou moins. Alors je vais simplement prendre la dernière observation qui est complète


# Sous ensemble de ceux vaccinés, groupé par pays.
country_vax <- vaxd[vaxd$iso_code %like% "^[a-zA-Z]{3}$", ]

# Seulement la dernière observation de chaque pays
country_vax <- country_vax %>% 
  group_by(location) %>%
slice(which.max(as.Date(date, '%Y/%m/%d')))

```


# Banque de données de vaccinations séparé par continent
```{r}
# Sous ensemble de ceux vacciné, groupé par continent
continent_vax <- vaxd[vaxd$iso_code %like% "OWID", ] %>% 
                mutate(location=factor(location))



#J'enlève l'union européenne
continent_vax <- continent_vax[continent_vax$location %in% c("Africa","Asia","Europe","North America","Oceania","South America","World"), ]

#Je prend seulement la dernière observations de chaque continent.
continent_vax <- continent_vax %>% 
  group_by(location) %>%
slice(which.max(as.Date(date, '%Y/%m/%d')))


```

# Manipulation de la banque de données de population mondiale
```{r}
# Je séléctionne les variabes importantes quant à la poulation par pays
country_pop <- country_pop_raw %>% 
    mutate(name=factor(name)) %>%
    select(c(name,`2020.0`, `2021.0`, `2022.0`))

# Je séléctionne les variables importantes quant à la poulation par continent.
continent_pop <- continent_pop_raw %>% 
    select(c(name,`2020.0`, `2021.0`, `2022.0`))


# Je renomme le nom de la colonne pour pouvoir la "merge" avec 
# la banque de données de vaccination.
names(country_pop)[1] <- "location"
names(continent_pop)[1] <- "location"
```


# Manipulation des donnes brutes d'espérance de vie
```{r}
# PAR PAYS, je prend juste 2021 pcq les différence d'une annee a lautre sont minime.
life_country <- life_country_raw %>% 
    mutate(name=factor(name)) %>% 
    select(c(name,`2021.0`)) %>% 
    na.omit()

names(life_country)[1] <- "location" 


# PAR CONTINENT
life_continent <- life_continent_raw %>% 
    mutate(name=factor(name)) %>% 
    select(c(name,`2021.0`)) %>% 
    na.omit()

names(life_continent)[1] <- "location"
  
```
