---
title: "descrption_practice"
author: "Emmanuel_Carranza"
date: "16/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#Il y a beaucoup de NA dans les variables mais si je les enlève dès le départ, je réduit ma banque de données de 92%. Ce qui n'est pas une bonne idée.
summary(vax_raw)

# J'ai Africa, Asia, Europe, european union, North America, Oceania, South America, World
# pcq europe = 50 pays
# et l'union européenne cest juste 28 pays, jvais garder juste l'europe
unique(continent_vax$location)

# tout les continents on autour de 300 observations
continent_most_entries <- continent_vax %>% 
    group_by(location) %>% 
    summarize(count=n()) %>%   
    arrange(desc(count))


#Ici j'ai juste 197 pays différent, alors que la banque de donne de vaccinations
#contient 235 pays.
str(country_pop$location)




#check tout les pays qui sont pas dans les deux dataset
# yen a 45 qui sont pas la dans les deux
setdiff(country_vax$location,country_pop$location)

#J'ai encore 235 pays
str(merged_vax_pop$location)

str(vaxd_country_max_date$location)
           
# Pour voir les pays qui ont le plus et moins d'observation
list_country_most_entries <- country_vax %>% 
    group_by(location) %>% 
    summarize(count=n()) %>% 
    arrange(desc(count))

list_country_most_entries

# J'ai 223 pays différent
str(country_vax$location)


# COMEME CA QUE TU CLASSE EN CROISSANT
low_life_exp <- life_country[order(as.integer(life_country$"2021.0"),decreasing = FALSE), ]


# PERFECT MATCH tout les pays sont la 100%
setdiff(life_country$location,country_pop$location)


# Ajout de la taille des populations pour les pays qui sont dans les 
# deux banques de données
merged_vax_pop <- merge(country_vax, country_pop,by = "location")

# Sélection seulement des dernieres observations par date.
merged_vax_pop <- merged_vax_pop %>% 
                          group_by(location) %>%
                          slice(which.max(as.Date(date, '%Y/%m/%d')))

library(rmarkdown)
paged_table(biggest_countries)

```

